Keyboard support
PlayPulseCom/flutter_wlroots pull request #9
Opened 2022-03-16 03:31 UTC by charafau

This PR targets https://github.com/PlayPulseCom/flutter_wlroots/issues/1

Current status:

- [x] Forward input from wlroots backend to the flutter engine. This includes handling the new keyboard signal emitted by wlroots and registering handlers for key events which call into the flutter engine API.

- [x]  Implement keyboard event handling in SurfaceWidget. This would involve introducing a focus node and adding a handler for keyboard events. Implementing focus-on-click vs focus-on-hover (or some other mechanism) is best left to the consumer, but the dart library should make this easy.

- [x]  Make sure the surface receives keyboard events correctly. This involves making a new message handler for keyboard events in native code which forwards the events to wlroots. This would be called by the SurfaceWidget when input events are received.

- [ ]  Make sure the surface receives/loses keyboard focus when the focus node receives/loses focus. This involves making a new message handler for managing focus changes in the native code, then forwarding that to wlroots. This would then be called by the SurfaceWidget when the focus node changes state.

^ We might want to add this in separate request when we have more than 1 SurfaceWidget and easy way to switch between them

2022-03-16 11:59 UTC, hansihe requested changes

2022-03-16 11:59 UTC, hansihe commented on src/key_mapping.cc
> +// flutter/flutter@dev/tools/gen_keycodes/bin/gen_keycodes.dart and should not
Is this file unmodified from the generator, or has there been modifications?

2022-03-16 11:59 UTC, hansihe commented on compositor_dart/lib/constants.dart
> +const Map<int, int> physicalToXkbMap = {
Where is this mapping from? Is there any reason not to do this on the C side where the other parts of the mapping live?

2022-03-16 11:59 UTC, hansihe commented on compositor_dart/lib/compositor_dart.dart
> +    });
This should likely be removed, debug code

2022-03-16 11:59 UTC, hansihe commented on compositor_dart/lib/surface.dart
> +          int? keycode = physicalToXkbMap[event.physicalKey.usbHidUsage];
Use the function for this in the compositor

2022-03-16 11:59 UTC, hansihe commented on compositor_dart/lib/surface.dart
> +          }
Is this necessarily `Down` OR `Up`? What about key repeat event?

It would at least be nice to do an `is` check on both of these branches, then debug print if we get an event type we didn't expect.

2022-03-16 11:59 UTC, hansihe commented on compositor_dart/lib/surface.dart
> +          print(event.character);
Remove debug print

2022-03-16 11:59 UTC, hansihe commented on src/input.c
> +	if (!context) {
inconsistent formatting

2022-03-16 11:59 UTC, hansihe commented on src/surface.c
> +	/* Note: this function only deals with keyboard focus. */
inconsistent formatting

2022-03-16 11:59 UTC, hansihe commented on src/surface.c
> -  view->surface = xdg_surface;
Any reason for this move?

2022-03-16 13:01 UTC, HrX03 commented on compositor_dart/lib/surface.dart
> +          }
Wlroots doesn't have a concept for repeat, instead it decides to "repeat" once it gets enough down events for the same key (at least by observing how it behaves + no enum entry for repeat)

2022-03-16 13:02 UTC, HrX03 commented on compositor_dart/lib/constants.dart
> +const Map<int, int> physicalToXkbMap = {
This is taken from the gtk embedding iirc and it's just a reversed version of the xkb to physical map. Imo it should be in dart as it's easier to handle there as in c, but I'm open to anything really

2022-03-16 13:13 UTC, HrX03 commented on include/jsmn.h
> +  JSMN_STRING = 3,
Why use 1 2 3 4 instead of the bit shifted constants?

2022-03-16 13:13 UTC, HrX03 commented on include/key_mapping.h
> +#endif  // KEYBOARD_MAP_H_
This + the c impl should be replaced with the xkb based methods

2022-03-16 13:13 UTC, HrX03 commented on src/input.c
> +  wlr_seat_keyboard_notify_key(instance->seat, message.timestamp / NS_PER_MS, message.keycode - 8, type);
By looking at various wl impls keyboard focus should be moved only on view focus, like when opening a new surface or when the user clicks the view to focus. We should change the flutter side to have one big global listener indeed instead of one for each surface as it doesn't really match with how wlroots handles keyboard

2022-03-16 13:13 UTC, HrX03 commented on src/surface.c
> -  view->surface = xdg_surface;
Not really, was having some issues and moved stuff around to test, just forgot to put it back where it once was

2022-03-16 13:55 UTC, hansihe commented on compositor_dart/lib/surface.dart
> +          }
It does seem like wlroots has the concept of repeats, as evident by `wlr_keyboard_set_repeat_info`.

So wlroots uses subsequent `PRESSED` events as the signal of a repeat key then? This should be converted to the `Repeat` event in the flutter engine on the C side.

2022-03-18 01:33 UTC, charafau commented on src/key_mapping.cc
> +// flutter/flutter@dev/tools/gen_keycodes/bin/gen_keycodes.dart and should not
original is from generator, this one is not. I will remove comment

2022-03-18 01:34 UTC, charafau commented on compositor_dart/lib/constants.dart
> +const Map<int, int> physicalToXkbMap = {
What @HrX03  said. This mapping is take from Linux embedder https://github.com/flutter/engine/blob/master/shell/platform/linux/key_mapping.cc#L20 
it's documented here https://github.com/flutter/flutter/blob/master/dev/tools/gen_keycodes/README.md

2022-03-18 01:40 UTC, charafau commented on compositor_dart/lib/surface.dart
> +          }
Basically what @HrX03  said. wlroots will send up events which will work as repeat.

2022-03-18 02:12 UTC, charafau commented on demo/lib/main.dart
> +    return Focus(
Focus doesn't work on surface at the moment. I think we can move that to point 4

2022-03-18 02:16 UTC, charafau commented on include/collection.h
> +#ifndef _COLLECTION_H
`collection.h` , `platform_channel.h` and `jsmn.h` are taken from `flutter-pi`  and are used for serializing arrays https://github.com/ardera/flutter-pi/tree/master/include

2022-03-18 02:18 UTC, charafau commented on include/platform_channel.h
> +#ifndef _METHODCHANNEL_H
makes sense,  should I paste that in the beginning of header ? https://github.com/ardera/flutter-pi/blob/master/LICENSE

2022-03-18 02:25 UTC, charafau commented on src/input.c
> +		&keyboard->device->keyboard->modifiers);
Good question, I will check gtk compositor and come back to it

2022-03-18 02:27 UTC, charafau commented on src/input.c
> +	struct fwr_keyboard *keyboard =	wl_container_of(listener, keyboard, key);
sorry about that, can we configure decide on some code formatting tool? maybe `clang-format` ?

2022-03-18 02:30 UTC, charafau commented on src/input.c
> +  wlr_keyboard_set_repeat_info(device->keyboard, 25, 600);
https://gitlab.freedesktop.org/lilydjwg/wlroots/-/blob/master/tinywl/tinywl.c#L232

2022-03-18 02:31 UTC, charafau commented on src/input.c
> +  wlr_seat_keyboard_notify_key(instance->seat, message.timestamp / NS_PER_MS, message.keycode - 8, type);
Yes, it's 1 surface for now.

2022-03-18 02:33 UTC, charafau commented on include/key_mapping.h
> +#endif  // KEYBOARD_MAP_H_
can you elaborate on that?

2022-03-18 02:37 UTC, charafau commented on include/jsmn.h
> +  JSMN_STRING = 3,
looks like original lib has bitshift operatoions but flutter-pi has constants. I reverted to bit shift operators because I'd rather no to modify extrenal library

2022-03-18 15:38 UTC, charafau commented on src/surface.c
> -  view->surface = xdg_surface;
Restored

2022-03-26 14:36 UTC, hansihe commented
Todos:
 * Remove `collections.h`, put asserts part into `asserts.h`
 * Revert unnecessary changes in `surface.c`

2022-03-31 13:25 UTC, merged

2022-03-31 13:25 UTC, hansihe commented
Thanks!